### ISSUE TITLE
Can not append keys to authorized_keys file

### ISSUE THREAD

**Issue by thomasalrin** [zuazo/ssh_authorized_keys-cookbook#13]
### Cookbook Version
0.5.0

### Chef Client Version
Chef: 13.8.5

### Platform Details
Red Hat Enterprise Linux Server release 7.4 (Maipo)

### Scenario
Appending ssh keys to authorized_keys file
But it is over writing

### Steps to Reproduce
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result
Append the key with the already existing keys in authorized_keys

### Actual Result
Each time it is over writing the authorized_keys file

**Comment by zuazo** [comment]
Sorry, but I think this request falls outside the scope of this cookbook. The idea is to manage full keys file using Chef. Appending to it will never be supported. Probably there are other cookbooks for it, search in the Supermarket.

https://github.com/zuazo/ssh_authorized_keys-cookbook/blob/master/README.md#ssh_authorize_key

> **Warning:** This definition uses the [Accumulator Pattern](http://docs.chef.io/definitions.html#many-recipes-one-definition). This implies that any SSH key added using other methods (such as **keys added by hand**) will be **deleted**.
