### ISSUE TITLE
I have used it successfully on AIX 7.1 

### ISSUE THREAD

**Issue by MVNW** [zuazo/ssh_authorized_keys-cookbook#8]
Well, it worked out of the box on AIX 7.1 powerpc

I used Chef: 12.11.18 on AIX 7100-00-03-1115, newer should work fine to. 
If you need any more info just ask.

With regards Mike

**Comment by zuazo** [comment]
Thanks for the feedback, @MVNW. It's really appreciated :wink:

**Comment by MVNW** [comment]
Your welcome :)

**Comment by zuazo** [comment]
Released in [`0.4.0`](https://github.com/zuazo/ssh_authorized_keys-cookbook/releases/tag/0.4.0).
